apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: verify-deployment
spec:
  params:
    - name: ibm-cloud-region
      description: Region where cluster is located
    - name: api-url
      description: API URL for interacting with IBM Cloud
      default: cloud.ibm.com
  workspaces:
    - name: source
  steps:
    - name: deploy-app
      image: ibmcom/pipeline-base-image:2.7
      env:
        - name: IBMCLOUD_API_KEY
          valueFrom:
            secretKeyRef:
              name: secure-properties
              key: apikey
      command: ["/bin/bash", "-c"]
      args:
        - set -e -o pipefail;
          ibmcloud login -a $(params.api-url) -r $(params.ibm-cloud-region);
          ibmcloud target --cf;
  steps:
   - name: verify-app
	   image: ibmcom/pipeline-base-image:2.7
		 ...
     command: ["/bin/bash", "-c"]
     args:
      - set -e -o pipefail;
	      ibmcloud login -a $(params.api-url) -r $(params
	      ibm-cloud-region);
	      ibmcloud target --cf;
        ibmcloud fn action invoke helloJava -r
        echo "return value="$?
        exit $?
        # Test the application function's integer return value
        if [ $? -eq 0 ]
        then
	         echo "Success"
	         exit 0
        else
	         echo "Failure" >&2
	         exit 1
         fi
         # Update the application invoke command to capture the JSON response
          response="$(ibmcloud fn action invoke helloJava -r)"

         # String to test for within the JSON response
          TEST='Congratulations'

         # Test the application function's JSON response as a string
          if [[ "$response" == *"$TEST"* ]]
          then
	           echo "Success"
	           #exit 0
         else
	          echo "Failure" >&2
	          #exit 1
         fi
